name: Check Virtualization Support

# 定义触发方式
on:
  workflow_dispatch: # 手动触发

jobs:
  check-virtualization:
    runs-on: windows-11-arm # 使用 Windows ARM64 运行器
    steps:
      - name: Check System Info
        run: systeminfo
        shell: cmd

      - name: Check Virtualization with PowerShell
        shell: pwsh
        run: |
          Get-ComputerInfo | Select-Object -Property WindowsProductName, HyperVisorPresent
          Get-CimInstance -ClassName Win32_Processor | Select-Object -Property VirtualizationFirmwareEnabled, VMMonitorModeExtensions
          Get-WindowsOptionalFeature -Online | Where-Object { $_.FeatureName -like "*Hyper-V*" }

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.8' # 明确指定 Java 17 的版本
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true

      - name: Verify Java Installation
        run: java -version
        shell: pwsh
      - name: Install Android SDK
        run: |
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-win-9477386_latest.zip
          unzip sdk-tools.zip -d android-sdk
          $env:ANDROID_HOME = "$PWD/android-sdk"
          yes | ./android-sdk/cmdline-tools/bin/sdkmanager.bat --sdk_root=$env:ANDROID_HOME "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;google_apis;arm64-v8a"
        shell: pwsh

      - name: Create AVD
        run: |
          echo "no" | ./android-sdk/cmdline-tools/bin/avdmanager.bat create avd -n test-avd -k "system-images;android-30;google_apis;arm64-v8a"
        shell: pwsh
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk

      - name: Start Emulator
        run: |
          $env:ANDROID_HOME/emulator/emulator -avd test-avd -no-window -no-audio
        shell: pwsh
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          ANDROID_AVD_HOME: ${{ github.workspace }}/.android/avd
