name: Check Virtualization Support

# 定义触发方式
on:
  workflow_dispatch: # 手动触发

jobs:
  check-virtualization:
    runs-on: windows-11-arm # 使用 Windows ARM64 运行器
    steps:
      - name: Check System Info
        run: systeminfo
        shell: cmd

      - name: Check Virtualization with PowerShell
        shell: pwsh
        run: |
          Get-ComputerInfo | Select-Object -Property WindowsProductName, HyperVisorPresent
          Get-CimInstance -ClassName Win32_Processor | Select-Object -Property VirtualizationFirmwareEnabled, VMMonitorModeExtensions
          Get-WindowsOptionalFeature -Online | Where-Object { $_.FeatureName -like "*Hyper-V*" }

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' # 使用 Java 21
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true

      - name: Verify Java Installation
        run: java -version
        shell: pwsh
      - name: Install Android SDK
        run: |
          # 下载最新命令行工具（需替换为实际 URL）
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip
          unzip sdk-tools.zip -d android-sdk
          $env:ANDROID_HOME = "$PWD/android-sdk"
          $env:PATH = "$env:ANDROID_HOME/cmdline-tools/bin;$env:PATH"
          # 清理缓存
          Remove-Item -Recurse -Force "$env:ANDROID_HOME/.android/cache" -ErrorAction SilentlyContinue
          # 接受许可
          echo "y" | ./android-sdk/cmdline-tools/bin/sdkmanager.bat --sdk_root=$env:ANDROID_HOME --licenses
          # 检查可用包
          ./android-sdk/cmdline-tools/bin/sdkmanager.bat --sdk_root=$env:ANDROID_HOME --list
          # 安装组件（带重试）
          for ($i = 1; $i -le 3; $i++) {
            ./android-sdk/cmdline-tools/bin/sdkmanager.bat --sdk_root=$env:ANDROID_HOME --channel=0 "platform-tools" "platforms;android-33" "emulator" "system-images;android-33;google_apis;arm64-v8a" && break
            echo "Retry $i failed, waiting 10s..."
            Start-Sleep -Seconds 10
          }
        shell: pwsh

      - name: Create AVD
        run: |
          echo "no" | ./android-sdk/cmdline-tools/bin/avdmanager.bat create avd -n test-avd -k "system-images;android-33;google_apis;arm64-v8a"
        shell: pwsh
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk

      - name: Start Emulator
        run: |
          $env:ANDROID_HOME/emulator/emulator -avd test-avd -no-window -no-audio
        shell: pwsh
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          ANDROID_AVD_HOME: ${{ github.workspace }}/.android/avd
          ANDROID_AVD_HOME: ${{ github.workspace }}/.android/avd
