name: Check Virtualization Support

# 定义触发方式
on:
  workflow_dispatch: # 手动触发

jobs:
  check-virtualization:
    runs-on: windows-arm64 # 使用 Windows ARM64 运行器
    steps:
      - name: Check system info
        run: systeminfo
        shell: cmd # 使用 cmd 执行 systeminfo

      - name: Check virtualization with PowerShell
        shell: pwsh
        run: |
          Get-ComputerInfo | Select-Object -Property WindowsProductName, HyperVisorPresent
          Get-CimInstance -ClassName Win32_Processor | Select-Object -Property VirtualizationFirmwareEnabled, VMMonitorModeExtensions
