name: Check Virtualization Support

# 定义触发方式
on:
  workflow_dispatch: # 手动触发

jobs:
  check-virtualization:
    runs-on: windows-11-arm # 使用 Windows ARM64 运行器
    steps:
      - name: Check System Info
        run: systeminfo
        shell: cmd

      - name: Check Virtualization with PowerShell
        shell: pwsh
        run: |
          Get-ComputerInfo | Select-Object -Property WindowsProductName, HyperVisorPresent
          Get-CimInstance -ClassName Win32_Processor | Select-Object -Property VirtualizationFirmwareEnabled, VMMonitorModeExtensions
          Get-WindowsOptionalFeature -Online | Where-Object { $_.FeatureName -like "*Hyper-V*" }

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' # 使用 Java 21
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true

      - name: Verify Java Installation
        run: java -version
        shell: pwsh
      - name: Install Android SDK Components
        run: |
          $env:ANDROID_HOME = "C:\Android\android-sdk"
          mkdir $env:ANDROID_HOME -ErrorAction SilentlyContinue
          # 下载 platform-tools
          curl -L -o platform-tools.zip https://dl.google.com/android/repository/platform-tools_r35.0.2-windows.zip
          unzip platform-tools.zip -d $env:ANDROID_HOME
          # 下载 system-images（若需模拟器）
          curl -L -o system-image.zip https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-34_r04.zip
          mkdir $env:ANDROID_HOME\system-images\android-34\google_apis -ErrorAction SilentlyContinue
          unzip system-image.zip -d $env:ANDROID_HOME\system-images\android-34\google_apis
          # 下载 emulator（若需模拟器）
          curl -L -o emulator.zip https://dl.google.com/android/repository/emulator-windows_arm64-35.1.18.zip
          unzip emulator.zip -d $env:ANDROID_HOME\emulator
          # 设置 PATH
          $env:PATH = "$env:ANDROID_HOME\platform-tools;$env:ANDROID_HOME\emulator;$env:PATH"
          # 验证
          adb version
          emulator -version
        shell: pwsh

      - name: Create AVD
        run: |
          # 下载命令行工具（仅用于 avdmanager）
          curl -L -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-win-12073019_latest.zip
          unzip cmdline-tools.zip -d $env:ANDROID_HOME\cmdline-tools
          echo "no" | $env:ANDROID_HOME\cmdline-tools\cmdline-tools\bin\avdmanager.bat create avd -n test-avd -k "system-images;android-34;google_apis;arm64-v8a"
        shell: pwsh
        env:
          ANDROID_HOME: C:\Android\android-sdk

      - name: Start Emulator
        run: |
          $env:ANDROID_HOME\emulator\emulator -avd test-avd -no-window -no-audio
        shell: pwsh
        env:
          ANDROID_HOME: C:\Android\android-sdk
          ANDROID_AVD_HOME: C:\Android\.android\avd
