name: Check Virtualization Support

# 定义触发方式
on:
  workflow_dispatch: # 手动触发

jobs:
  check-virtualization:
    runs-on: windows-11-arm # 使用 Windows ARM64 运行器
    steps:
      - name: Check System Info
        run: systeminfo
        shell: cmd

      - name: Check Virtualization with PowerShell
        shell: pwsh
        run: |
          Get-ComputerInfo | Select-Object -Property WindowsProductName, HyperVisorPresent
          Get-CimInstance -ClassName Win32_Processor | Select-Object -Property VirtualizationFirmwareEnabled, VMMonitorModeExtensions
          Get-WindowsOptionalFeature -Online | Where-Object { $_.FeatureName -like "*Hyper-V*" }

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' # 使用 Java 21
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true

      - name: Verify Java Installation
        run: java -version
        shell: pwsh
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '33'
          components: 'platform-tools,platforms;android-33,emulator,system-images;android-33;google_apis;arm64-v8a'

      - name: Verify Android SDK
        run: |
          adb version
          $env:ANDROID_HOME/tools/bin/sdkmanager.bat --list
        shell: pwsh
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk

      - name: Create AVD
        run: |
          echo "no" | $env:ANDROID_HOME/tools/bin/avdmanager.bat create avd -n test-avd -k "system-images;android-33;google_apis;arm64-v8a"
        shell: pwsh
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk

      - name: Start Emulator
        run: |
          $env:ANDROID_HOME/emulator/emulator -avd test-avd -no-window -no-audio
        shell: pwsh
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          ANDROID_AVD_HOME: ${{ github.workspace }}/.android/avd
